### ISSUE TITLE
Calibrated and un-calibrated data

### ISSUE THREAD

**Issue by vangalvin** [sparkfun/Qwiic_Spectral_Sensor_AS726X#1]
I am using an AS7263 and was trying to do a comparison with the calibrated and uncalibrated data however both seem to have exactly the same output?

The other issue I am seeing is that when using sensor.printMeasurements();  the results are a reading with 2 decimal places however when using sensor.getR() there are no decimal places.

**Comment by nseidle** [comment]
Uncal data are ints, cal data are floats so I would be surprised if they had identical output. Can you share your code so we can replicate your issue? 

Sorry! There's an error in printMeasurements() - [these lines](https://github.com/sparkfun/SparkFun_AS726X_Arduino_Library/blob/master/src/AS726X.cpp#L166) should not be printing a float (the ', 2') since getR() returns an int. Use

    Serial.print(sensor.getR());

instead. We'll get this fixed shortly.

**Comment by vangalvin** [comment]
Thanks, This morning when i turned the unit on it out of the blue I am getting a different reading from the sensors. Looks like I am however going to have to use the AT interface as I need to use both the AS7262 and AS7263 at the same time and need to make the circuit as small as possible so a MUX is not really going to be an option and there seems to be no way to change the i2c address.

The the readings I am getting from the AS7263 are as follows.
`Un-Calibrated Data - AS7263 - using getX()
UR: 146 US: 57 UT: 15 UU: 11 UV: 10 UW: 5
Calibrated Data - AS7263 - using getCalibratedX()
CR: 202.37 CS: 63.75 CT: 17.23 CU: 10.74 CV: 10.51 CW: 6.21
Un-Calibrated Data - AS726X - using printUncalibratedMeasurements();
Reading: R[10010010] S[111001] T[1111] U[1011] V[1010] W[101] tempF[69.8]
Calibrated Data - AS726X - using printMeasurements()
Reading: R[202.37] S[63.75] T[17.23] U[10.74] V[10.51] W[6.21] tempF[68.0]

Calibrated Data - AS7262 - using getCalibratedXColourX]()
CV: 414.04 CB: 346.99 CG: 401.32 CY: 405.83 CO: 377.95 CR: 209.68
Calibrated Data - AS7262 - using getXColourX()
UV: 346 UB: 277 UG: 350 UY: 424 UO: 369 UR: 235
Un-Calibrated Data - AS726X - using printUncalibratedMeasurements();
Reading: V[101011010] B[100010110] G[101011110] Y[110101000] O[101110001] R[11101011] tempF[64.4]
Calibrated Data - AS726X - using printMeasurements()
Reading: V[414.04] B[348.24] G[401.32] Y[405.83] O[377.95] R[209.68] tempF[62.6]`

The test code I put together is noting special as I decided to step back and make sure the sensors were working correctly and isolate and possibility of something in my main code causing issues. What was strange is in my main code the output for printUncalibratedMeasurements(); was initially not binary.

`#include "AS726X.h"
AS726X sensor;

byte GAIN = 2;
byte MEASUREMENT_MODE = 3;
byte dump = 1;
void setup() {
    sensor.begin(Wire, GAIN, MEASUREMENT_MODE);
}

void loop() {
    sensor.takeMeasurementsWithBulb();
delay(200);
if(dump == 0){
  Serial.println("Un-Calibrated Data - AS726X - using printUncalibratedMeasurements();");
  sensor.printUncalibratedMeasurements();
  Serial.println("Calibrated Data - AS726X - using printMeasurements()");
  sensor.printMeasurements();
}
if(dump == 1){
    Serial.println("Calibrated Data - AS7262 - using getCalibratedXColourX()");
    Serial.print("CV: ");
    Serial.print(sensor.getCalibratedViolet(), 2);
    Serial.print(" CB: ");
    Serial.print(sensor.getCalibratedBlue(), 2);  
    Serial.print(" CG: ");
    Serial.print(sensor.getCalibratedGreen(), 2);
    Serial.print(" CY: ");
    Serial.print(sensor.getCalibratedYellow(), 2);
    Serial.print(" CO: ");
    Serial.print(sensor.getCalibratedOrange(), 2);
    Serial.print(" CR: ");
    Serial.println(sensor.getCalibratedRed(), 2);
    Serial.println("Calibrated Data - AS7262 - using getXColourX()");
    Serial.print("UV: ");
    Serial.print(sensor.getViolet());
    Serial.print(" UB: ");
    Serial.print(sensor.getBlue());
    Serial.print(" UG: ");
    Serial.print(sensor.getGreen());
    Serial.print(" UY: ");
    Serial.print(sensor.getYellow());
    Serial.print(" UO: ");
    Serial.print(sensor.getOrange());
    Serial.print(" UR: ");
    Serial.println(sensor.getRed());
}
if(dump == 2){
    Serial.println("Un-Calibrated Data - AS7263 - using getX()");
    Serial.print("UR: ");
    Serial.print(sensor.getR());
    Serial.print(" US: ");
    Serial.print(sensor.getS());
    Serial.print(" UT: ");
    Serial.print(sensor.getT());
    Serial.print(" UU: ");
    Serial.print(sensor.getU());
    Serial.print(" UV: ");
    Serial.print(sensor.getV());
    Serial.print(" UW: ");
    Serial.println(sensor.getW());
    Serial.println("Calibrated Data - AS7263 - using getCalibratedX()");
    Serial.print("CR: ");
    Serial.print(sensor.getCalibratedR(), 2);
    Serial.print(" CS: ");
    Serial.print(sensor.getCalibratedS(), 2);  
    Serial.print(" CT: ");
    Serial.print(sensor.getCalibratedT(), 2);
    Serial.print(" CU: ");
    Serial.print(sensor.getCalibratedU(), 2);
    Serial.print(" CV: ");
    Serial.print(sensor.getCalibratedV(), 2);
    Serial.print(" CW: ");
    Serial.println(sensor.getCalibratedW(), 2);
}
}
`

**Comment by nseidle** [comment]
WRT to two sensors on the same bus: There is not a command to easily change the I2C address but the [sensor's firmware](https://github.com/sparkfun/Qwiic_Spectral_Sensor_AS726X/blob/master/Firmware/Firmware%20for%20AT25SF041/AS7262/ams_SDldr_AS7262_v2p0p3_Flash_512K.BIN) (provided by AMS) is programmed on to the SPI flash as the breakout board exits our production line. You *could* modify the hex firmware (the I2C address has to be in there somewhere) and then reprogram one of your boards. Just a wild thought.

**Comment by vangalvin** [comment]
@nseidle Had a quick look and noting really jumps out, did a search for the address but cant seem to find it. Its a shame ams has not released the source for this as it would definatly be handy.
If i can find it and are able to change it will let you know as i think there are a few others out there who are having a similar issue from what I have seen. Most however have opted to use an I2C mux.

**Comment by shintaehwan** [comment]
i want use my as7263..with mega.. but i don.t know how to use ... 
can i know arduino code ? ...
![kakaotalk_20181127_145735798](https://user-images.githubusercontent.com/45381428/49062547-e43bc900-f257-11e8-9318-7050c8634323.jpg)

**Comment by nseidle** [comment]
I'm going to close this issue since the original issue was an I2C address issue that can be solved with a [Qwiic mux](https://www.sparkfun.com/products/14685).

@shintaehwan - We offer an [Arduino library](https://github.com/sparkfun/SparkFun_AS726X_Arduino_Library) that you can install via the Arduino library manager. Please see the [hookup guide](https://learn.sparkfun.com/tutorials/as726x-nirvi) for more info.

**Comment by shintaehwan** [comment]
[image: image.png]
[image: image.png]

2018년 11월 28일 (수) 오전 11:40, Nathan Seidle <notifications@github.com>님이 작성:

**Comment by kbickham** [comment]
Buying a product to multiplex instead of changing an i2c address is not a real solution.
