### ISSUE TITLE
Incompatible with Artemis

### ISSUE THREAD

**Issue by nseidle** [sparkfun/Qwiic_Spectral_Sensor_AS726X#4]
Board isn't working with Artemis. I'm not entirely sure where it's failing but there's a handful of issues with this lib that might be part of it:

* Don't Wire.begin inside a library
* Don't Serial.print inside a library
* Create functions called setGain(), setMeasurementMode(). Don't pass to begin.
* Consider an .available() function if sensor takes time to take measurement. Don't write blocking code if possible.

Nits:

* Re-write example one to return sensor values. Let user print what they want.
* Please expand on the library.properties paragraph. 
* Please name library with what it does (I recommend "SparkFun AS726x Spectral Sensor")

**Comment by bboyho** [comment]
I briefly checked in with Andy and it looks like most of these issues were addressed in [https://github.com/sparkfun/SparkFun_AS726X_Arduino_Library/issues/1](https://github.com/sparkfun/SparkFun_AS726X_Arduino_Library/issues/1) and the library updates [https://github.com/sparkfun/SparkFun_AS726X_Arduino_Library/releases](https://github.com/sparkfun/SparkFun_AS726X_Arduino_Library/releases):

* Compiling for Artemis
* Don't Wire.begin inside a library
* Don't Serial.print inside a library
* Consider an .available() function if sensor takes time to take measurement. Don't write blocking code if possible.

**Comment by stephenf7072** [comment]
Confirming that I've had it working with the Artemis for a good couple of months (the issue can probably be closed).

**Comment by nseidle** [comment]
@stephenf7072 - Thanks for the reminder and test confirmation! Closing.
