### ISSUE TITLE
I2C_AS72XX_SLAVE_STATUS_REG returns 0x82

### ISSUE THREAD

**Issue by jajberni** [sparkfun/Qwiic_Spectral_Sensor_AS726X#5]
Normally the device works without problems, but after some hours of continuous operation, the device stops. 

I noticed that reading the I2C_AS72XX_SLAVE_STATUS_REG returns 0x82 no matter what. Therefore, the condition `if ((status & I2C_AS72XX_SLAVE_TX_VALID) == 0)` is never met in the virtualReadRegister operations. 

Is there a way to 'soft reset' the device without using the virtual register operations?

A hard reset normally fits the issue, but it comes back at some point.

**Comment by nseidle** [comment]
Yep. Please see [softReset()](https://github.com/sparkfun/SparkFun_AS726X_Arduino_Library/blob/master/src/AS726X.cpp#L292).

**Comment by jajberni** [comment]
Unfortunately, this function uses the function [uint8_t AS726X::virtualReadRegister(uint8_t virtualAddr)](https://github.com/sparkfun/SparkFun_AS726X_Arduino_Library/blob/63e75a0c676ab6a9f6aea8fb085095bc575fd7ed/src/AS726X.cpp#L301), so it doesn't help.
